# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artis',
            new_name='artist',
        ),
    ]
