# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
