# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180729_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='album_logo'),
        ),
    ]
