# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180729_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to='lagu'),
        ),
    ]
